<?php

if (! defined('ABSPATH')) {
	exit;
}

final class EPV2_Source_Library {
	public static function recommended(): array {
		$sources = [
			[
				'name' => 'Bundesregierung',
				'type' => 'rss',
				'url' => 'https://www.bundesregierung.de/breg-de/service/newsletter-und-abos/rss-newsfeed',
				'language' => 'de',
				'category_bias' => 'politik',
				'priority' => 10,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Официальные пресс-релизы правительства ФРГ. Amtliche Werke, безопасный источник для автоматизированного сбора и рерайта.',
			],
			[
				'name' => 'Deutscher Bundestag',
				'type' => 'rss',
				'url' => 'https://www.bundestag.de/services/rss/',
				'language' => 'de',
				'category_bias' => 'politik',
				'priority' => 10,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Официальные парламентские материалы и законодательная повестка. Официальные документы не охраняются копирайтом.',
			],
			[
				'name' => 'ARD Tagesschau',
				'type' => 'rss',
				'url' => 'https://www.tagesschau.de/index~rss2.xml',
				'language' => 'de',
				'category_bias' => 'deutschland',
				'priority' => 9,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Общественно-правовой вещатель. Разрешён только глубокий фактологический рерайтинг без копирования формулировок.',
			],
			[
				'name' => 'Deutschlandfunk',
				'type' => 'rss',
				'url' => 'https://www.deutschlandfunk.de/rss-angebot-102.html',
				'language' => 'de',
				'category_bias' => 'europa',
				'priority' => 8,
				'fetch_interval' => 2400,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Общественно-правовое радио. Использовать только факты, без копирования языковой структуры оригинала.',
			],
			[
				'name' => 'DW Germany EN',
				'type' => 'rss',
				'url' => 'https://rss.dw.com/rdf/rss-en-ger',
				'language' => 'en',
				'category_bias' => 'deutschland',
				'priority' => 8,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Официальный RSS Deutsche Welle по Германии. Использовать как дополнительный фактологический источник и supporting feed.',
			],
			[
				'name' => 'DW Europe EN',
				'type' => 'rss',
				'url' => 'https://rss.dw.com/rdf/rss-en-eu',
				'language' => 'en',
				'category_bias' => 'europa',
				'priority' => 8,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Официальный RSS Deutsche Welle по Европе. Хорош для corroboration и контекста по ЕС.',
			],
			[
				'name' => 'DW World EN',
				'type' => 'rss',
				'url' => 'https://rss.dw.com/rdf/rss-en-world',
				'language' => 'en',
				'category_bias' => 'world',
				'priority' => 8,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Официальный RSS Deutsche Welle по мировой повестке. Добавляет устойчивый внешний слой beyond Google News и Bing.',
			],
			[
				'name' => 'Handelsblatt',
				'type' => 'rss',
				'url' => 'https://www.handelsblatt.com/contentexpo',
				'language' => 'de',
				'category_bias' => 'wirtschaft',
				'priority' => 7,
				'fetch_interval' => 3600,
				'is_active' => 0,
				'risk_level' => 'high',
				'notes' => 'Коммерческое издание с высоким правовым риском. Использовать только как триггер для фактологического рерайта.',
			],
			[
				'name' => 'DER SPIEGEL via Google News',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=site%3Aspiegel.de&hl=de&gl=DE&ceid=DE:de',
				'language' => 'de',
				'category_bias' => 'politik',
				'priority' => 6,
				'fetch_interval' => 3600,
				'is_active' => 0,
				'risk_level' => 'high',
				'notes' => 'Только через Google News RSS и только как фактологический сигнал. Прямой парсинг Spiegel запрещён.',
			],
			[
				'name' => 'Google News Ukraine',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Ukraine&hl=uk&gl=UA&ceid=UA:uk',
				'language' => 'uk',
				'category_bias' => 'ukraine',
				'priority' => 7,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Google News RSS для украинской языковой витрины. Использовать как сигнал, затем делать глубокий фактологический рерайт.',
			],
			[
				'name' => 'Google News Politik DE',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Politik+Deutschland+Bundestag+Regierung&hl=de&gl=DE&ceid=DE:de',
				'language' => 'de',
				'category_bias' => 'politik',
				'priority' => 8,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Политический Google News-поток для Германии и федеральной повестки.',
			],
			[
				'name' => 'Google News Wirtschaft DE',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Wirtschaft+Deutschland+Inflation+Arbeitsmarkt&hl=de&gl=DE&ceid=DE:de',
				'language' => 'de',
				'category_bias' => 'wirtschaft',
				'priority' => 8,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Экономический Google News-поток для Германии: инфляция, рынок труда, бизнес.',
			],
			[
				'name' => 'Google News Europa DE',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Europa+EU+Br%C3%BCssel&hl=de&gl=DE&ceid=DE:de',
				'language' => 'de',
				'category_bias' => 'europa',
				'priority' => 7,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Европейский Google News-поток для ЕС, Брюсселя и общеевропейской повестки.',
			],
			[
				'name' => 'Google News Welt DE',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Welt+USA+China+Nahost+Asien&hl=de&gl=DE&ceid=DE:de',
				'language' => 'de',
				'category_bias' => 'world',
				'priority' => 7,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Welt-Signale fuer USA, Asien, Nahost und globale Themen.',
			],
			[
				'name' => 'Google News Leben in Deutschland DE',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=BAMF+B%C3%BCrgergeld+Integration+Jobcenter+Deutschland&hl=de&gl=DE&ceid=DE:de',
				'language' => 'de',
				'category_bias' => 'leben-in-deutschland',
				'priority' => 8,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Практический Google News-поток по интеграции, пособиям, документам и жизни в Германии.',
			],
			[
				'name' => 'Google News World EN',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en',
				'language' => 'en',
				'category_bias' => 'world',
				'priority' => 6,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Google News RSS для английской витрины и международной повестки. Использовать как сигнал, а не как источник прямого копирования.',
			],
			[
				'name' => 'Google News Politics EN',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Germany+politics+government+bundestag&hl=en-US&gl=US&ceid=US:en',
				'language' => 'en',
				'category_bias' => 'politik',
				'priority' => 8,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Англоязычный Google News-поток по политике Германии и Европы.',
			],
			[
				'name' => 'Google News Economy EN',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Germany+economy+inflation+jobs+europe&hl=en-US&gl=US&ceid=US:en',
				'language' => 'en',
				'category_bias' => 'wirtschaft',
				'priority' => 8,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Англоязычный Google News-поток по экономике, рынку труда и бизнесу.',
			],
			[
				'name' => 'Google News Germany EN',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Germany+society+migration+schools+housing&hl=en-US&gl=US&ceid=US:en',
				'language' => 'en',
				'category_bias' => 'deutschland',
				'priority' => 7,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Англоязычный поток по обществу, миграции, школам, жилью и социальной повестке Германии.',
			],
			[
				'name' => 'Google News Culture EN',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Munich+culture+festival+exhibition+concert&hl=en-US&gl=US&ceid=US:en',
				'language' => 'en',
				'category_bias' => 'kultur',
				'priority' => 6,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Англоязычный культурный поток для Мюнхена и Германии.',
			],
			[
				'name' => 'Google News Sport EN',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Bundesliga+FC+Bayern+Munich+sport&hl=en-US&gl=US&ceid=US:en',
				'language' => 'en',
				'category_bias' => 'sport',
				'priority' => 7,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Англоязычный спортивный поток для Бундеслиги, Баварии и Германии.',
			],
			[
				'name' => 'Google News Політика UK',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=%D0%9D%D1%96%D0%BC%D0%B5%D1%87%D1%87%D0%B8%D0%BD%D0%B0+%D0%BF%D0%BE%D0%BB%D1%96%D1%82%D0%B8%D0%BA%D0%B0+%D0%84%D0%A1&hl=uk&gl=UA&ceid=UA:uk',
				'language' => 'uk',
				'category_bias' => 'politik',
				'priority' => 8,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Украиноязычный Google News-поток по политике Германии, ЄС и Украины.',
			],
			[
				'name' => 'Google News Економіка UK',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=%D0%B5%D0%BA%D0%BE%D0%BD%D0%BE%D0%BC%D1%96%D0%BA%D0%B0+%D0%9D%D1%96%D0%BC%D0%B5%D1%87%D1%87%D0%B8%D0%BD%D0%B8+%D0%84%D0%A1+%D1%96%D0%BD%D1%84%D0%BB%D1%8F%D1%86%D1%96%D1%8F&hl=uk&gl=UA&ceid=UA:uk',
				'language' => 'uk',
				'category_bias' => 'wirtschaft',
				'priority' => 8,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Украиноязычный поток по экономике Германии и Европы.',
			],
			[
				'name' => 'Google News Європа UK',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=%D0%84%D0%A1+%D0%84%D0%B2%D1%80%D0%BE%D0%BF%D0%B0+%D0%91%D1%80%D1%8E%D1%81%D1%81%D0%B5%D0%BB%D1%8C&hl=uk&gl=UA&ceid=UA:uk',
				'language' => 'uk',
				'category_bias' => 'europa',
				'priority' => 7,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Украиноязычный европейский поток по ЕС и общеевропейской повестке.',
			],
			[
				'name' => 'Google News Світ UK',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=%D0%A1%D0%B2%D1%96%D1%82+%D0%A1%D0%A8%D0%90+%D0%9A%D0%B8%D1%82%D0%B0%D0%B9+%D0%91%D0%BB%D0%B8%D0%B7%D1%8C%D0%BA%D0%B8%D0%B9+%D0%A1%D1%85%D1%96%D0%B4+%D0%90%D0%B7%D1%96%D1%8F&hl=uk&gl=UA&ceid=UA:uk',
				'language' => 'uk',
				'category_bias' => 'world',
				'priority' => 7,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Світові сигнали для США, Азії, Близького Сходу та глобальних тем.',
			],
			[
				'name' => 'Google News Життя в Німеччині UK',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=%D0%91%D0%90%D0%9C%D0%A4+Jobcenter+B%C3%BCrgergeld+%D0%9D%D1%96%D0%BC%D0%B5%D1%87%D1%87%D0%B8%D0%BD%D0%B0&hl=uk&gl=UA&ceid=UA:uk',
				'language' => 'uk',
				'category_bias' => 'leben-in-deutschland',
				'priority' => 8,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Украиноязычный поток по документам, інтеграції, роботі та соціальним правилам у Німеччині.',
			],
			[
				'name' => 'Google News Культура UK',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=%D0%BA%D1%83%D0%BB%D1%8C%D1%82%D1%83%D1%80%D0%B0+%D0%9C%D1%8E%D0%BD%D1%85%D0%B5%D0%BD+%D0%B2%D0%B8%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B0+%D0%BA%D0%BE%D0%BD%D1%86%D0%B5%D1%80%D1%82&hl=uk&gl=UA&ceid=UA:uk',
				'language' => 'uk',
				'category_bias' => 'kultur',
				'priority' => 6,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Украиноязычный поток по культурным событиям в Мюнхені, Німеччині та Європі.',
			],
			[
				'name' => 'Google News Спорт UK',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=%D0%91%D1%83%D0%BD%D0%B4%D0%B5%D1%81%D0%BB%D1%96%D0%B3%D0%B0+%D0%91%D0%B0%D0%B2%D0%B0%D1%80%D1%96%D1%8F+%D0%9C%D1%8E%D0%BD%D1%85%D0%B5%D0%BD+%D1%81%D0%BF%D0%BE%D1%80%D1%82&hl=uk&gl=UA&ceid=UA:uk',
				'language' => 'uk',
				'category_bias' => 'sport',
				'priority' => 7,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Украиноязычный спортивный поток по Бундеслізі, Баварії та спорту в Німеччині.',
			],
			[
				'name' => 'Google News Sport DE',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Sport+M%C3%BCnchen+OR+Bundesliga&hl=de&gl=DE&ceid=DE:de',
				'language' => 'de',
				'category_bias' => 'sport',
				'priority' => 7,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Спортивный Google News-поток как сигнал для фактического рерайта.',
			],
			[
				'name' => 'Google News Kultur DE',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=Kultur+M%C3%BCnchen+OR+Ausstellung+OR+Konzert&hl=de&gl=DE&ceid=DE:de',
				'language' => 'de',
				'category_bias' => 'kultur',
				'priority' => 6,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Культурный Google News-поток как сигнал для анонсов и культурной повестки.',
			],
			[
				'name' => 'IW Köln',
				'type' => 'rss',
				'url' => 'https://www.iwkoeln.de/rss/iw-komplett.xml',
				'language' => 'de',
				'category_bias' => 'wirtschaft',
				'priority' => 7,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'low',
				'notes' => 'Научно-исследовательский институт. Требуется корректное указание источника данных.',
			],
			[
				'name' => 'European Parliament',
				'type' => 'rss',
				'url' => 'https://www.europarl.europa.eu/at-your-service/de/stay-informed/rss-feeds',
				'language' => 'de',
				'category_bias' => 'europa',
				'priority' => 9,
				'fetch_interval' => 2400,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Официальный источник Европарламента. Директивы и помощь Украине от ЕС.',
			],
			[
				'name' => 'PORTAL BUND',
				'type' => 'rss',
				'url' => 'https://www.service.bund.de/Content/DE/Service/RSS/RSS-Meldungsuebersicht/meldungen_node.html',
				'language' => 'de',
				'category_bias' => 'leben-in-deutschland',
				'priority' => 8,
				'fetch_interval' => 2400,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Агрегатор официальных RSS министерств ФРГ. Полезен для Bürgergeld, пенсий и соцсферы.',
			],
			[
				'name' => 'muenchen.de Rathaus Umschau',
				'type' => 'rss',
				'url' => 'http://www.muenchen.info/pia/RSS/RSS.xml',
				'language' => 'de',
				'category_bias' => 'münchen',
				'priority' => 10,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Официальный портал Мюнхена. Городские новости, ведомства, транспорт, предупреждения.',
			],
			[
				'name' => 'MVG Betriebsmeldungen',
				'type' => 'scrape',
				'url' => 'https://www.mvg.de/services/betriebsaenderungen.html',
				'language' => 'de',
				'category_bias' => 'münchen',
				'priority' => 10,
				'fetch_interval' => 900,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Официальные изменения движения MVG: U-Bahn, Bus, Tram, замены и ограничения. Высокая практическая ценность.',
			],
			[
				'name' => 'München Verkehr / Baustellen',
				'type' => 'scrape',
				'url' => 'https://stadt.muenchen.de/infos/baustellen-verkehrseinschraenkungen.html',
				'language' => 'de',
				'category_bias' => 'münchen',
				'priority' => 9,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Официальные дорожные работы, ограничения движения и перекрытия в Мюнхене.',
			],
			[
				'name' => 'Deutsche Bahn München/Bayern Presse',
				'type' => 'scrape',
				'url' => 'https://www.deutschebahn.com/de/presse/presse-regional/pr-muenchen-de',
				'language' => 'de',
				'category_bias' => 'bayern',
				'priority' => 9,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Официальные региональные сообщения Deutsche Bahn по Мюнхену и Баварии: ограничения, ремонт, режим движения.',
			],
			[
				'name' => 'S-Bahn München',
				'type' => 'scrape',
				'url' => 'https://www.s-bahn-muenchen.de/fahren/betriebslage',
				'language' => 'de',
				'category_bias' => 'münchen',
				'priority' => 10,
				'fetch_interval' => 900,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Официальная оперативная обстановка S-Bahn München: задержки, сбои, замены и ограничения.',
			],
			[
				'name' => 'RIS München',
				'type' => 'rss',
				'url' => 'https://risi.muenchen.de/risi/rss?feed=BV-Empfehlungen',
				'language' => 'de',
				'category_bias' => 'münchen',
				'priority' => 8,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Open Data под лицензией dl-by-de 2.0. Нужна программная атрибуция мэрии Мюнхена и лицензии.',
			],
			[
				'name' => 'StMI Bayern',
				'type' => 'rss',
				'url' => 'https://www.stmi.bayern.de/service/rss-service/',
				'language' => 'de',
				'category_bias' => 'bayern',
				'priority' => 9,
				'fetch_interval' => 2400,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Официальные сводки МВД Баварии о безопасности, интеграции и помощи Украине.',
			],
			[
				'name' => 'BR24',
				'type' => 'rss',
				'url' => 'https://nachrichtenfeeds.br.de/rdf/boards/QXAPkQJ',
				'language' => 'de',
				'category_bias' => 'bayern',
				'priority' => 8,
				'fetch_interval' => 2400,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Общественно-правовой вещатель Баварии. Только фактологический рерайтинг.',
			],
			[
				'name' => 'München Klinik',
				'type' => 'rss',
				'url' => 'https://www.muenchen-klinik.de/rss/',
				'language' => 'de',
				'category_bias' => 'münchen',
				'priority' => 6,
				'fetch_interval' => 7200,
				'is_active' => 1,
				'risk_level' => 'low',
				'notes' => 'Пресс-релизы клиник города, здравоохранение и мероприятия для пациентов.',
			],
			[
				'name' => 'Abendzeitung München via Google News',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=site%3Aabendzeitung-muenchen.de&hl=de&gl=DE&ceid=DE:de',
				'language' => 'de',
				'category_bias' => 'münchen',
				'priority' => 5,
				'fetch_interval' => 3600,
				'is_active' => 0,
				'risk_level' => 'high',
				'notes' => 'Коммерческая газета с высоким риском. Использовать только как сигнал через Google News.',
			],
			[
				'name' => 'Kicker OPML',
				'type' => 'rss',
				'url' => 'https://newsfeed.kicker.de/opml',
				'language' => 'de',
				'category_bias' => 'sport',
				'priority' => 7,
				'fetch_interval' => 2400,
				'is_active' => 0,
				'risk_level' => 'high',
				'notes' => 'Коммерческий спорт-ресурс. Только результаты и факты матчей, без аналитики.',
			],
			[
				'name' => 'FC Bayern Official',
				'type' => 'rss',
				'url' => 'https://fcbayern.com/en/api/rss/content',
				'language' => 'en',
				'category_bias' => 'sport',
				'priority' => 7,
				'fetch_interval' => 2400,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Официальный клубный пресс-фид. Использовать для фактов о трансферах, травмах и анонсах.',
			],
			[
				'name' => 'muenchen.de Veranstaltungen',
				'type' => 'scrape',
				'url' => 'https://www.muenchen.de/veranstaltungen/events',
				'language' => 'de',
				'category_bias' => 'kultur',
				'priority' => 6,
				'fetch_interval' => 7200,
				'is_active' => 0,
				'risk_level' => 'low',
				'notes' => 'HTML-календарь событий Мюнхена. Нужен DOM/XPath-парсинг для анонсов мероприятий.',
			],
			[
				'name' => 'BAMF',
				'type' => 'rss',
				'url' => 'https://www.bamf.de/DE/Service/Abonnieren/RSS/rss_node.html',
				'language' => 'de',
				'category_bias' => 'leben-in-deutschland',
				'priority' => 10,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Фундаментальный источник по миграции, убежищу, интеграции и языковым курсам.',
			],
			[
				'name' => 'Germany4Ukraine',
				'type' => 'scrape',
				'url' => 'https://www.germany4ukraine.de/EN/aktuelles/seite_node.html',
				'language' => 'de',
				'category_bias' => 'leben-in-deutschland',
				'priority' => 9,
				'fetch_interval' => 3600,
				'is_active' => 0,
				'risk_level' => 'safe',
				'notes' => 'Официальный правительственный хаб для украинцев. Нужен HTML-парсинг страницы новостей.',
			],
			[
				'name' => 'Bundesagentur für Arbeit',
				'type' => 'scrape',
				'url' => 'https://www.arbeitsagentur.de/presse/presse-archiv',
				'language' => 'de',
				'category_bias' => 'leben-in-deutschland',
				'priority' => 8,
				'fetch_interval' => 3600,
				'is_active' => 0,
				'risk_level' => 'safe',
				'notes' => 'Пресс-архив BA. Нужен HTML-парсинг раздела для трудоустройства и статистики.',
			],
			[
				'name' => 'BMAS',
				'type' => 'rss',
				'url' => 'https://www.bmas.de/DE/Service/Newsletter/RSS/rss.html',
				'language' => 'de',
				'category_bias' => 'leben-in-deutschland',
				'priority' => 9,
				'fetch_interval' => 2400,
				'is_active' => 1,
				'risk_level' => 'safe',
				'notes' => 'Официальные изменения по Bürgergeld, рынку труда и социальной политике.',
			],
			[
				'name' => 'Jobcenter München',
				'type' => 'scrape',
				'url' => 'https://jobcenter-muenchen.de/ueber-uns/presse/',
				'language' => 'de',
				'category_bias' => 'leben-in-deutschland',
				'priority' => 8,
				'fetch_interval' => 3600,
				'is_active' => 0,
				'risk_level' => 'safe',
				'notes' => 'Локальная специфика Jobcenter München. Нужен кастомный HTML-парсинг раздела прессы.',
			],
			[
				'name' => 'Ukrinform DE',
				'type' => 'scrape',
				'url' => 'https://www.ukrinform.de/',
				'language' => 'de',
				'category_bias' => 'ukraine',
				'priority' => 10,
				'fetch_interval' => 1800,
				'is_active' => 0,
				'risk_level' => 'moderate',
				'notes' => 'Господдержанное агентство Украины. Обязательная гиперссылка на ukrinform.net не ниже первого абзаца.',
			],
			[
				'name' => 'UNIAN',
				'type' => 'rss',
				'url' => 'https://rss.unian.net/site/news_ukr.rss',
				'language' => 'uk',
				'category_bias' => 'ukraine',
				'priority' => 8,
				'fetch_interval' => 1800,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Коммерческое агентство. Только фактологический рерайтинг с обязательной ссылкой на источник.',
			],
			[
				'name' => 'Ukrainisches Haus München / LMU',
				'type' => 'scrape',
				'url' => 'http://www.ukrainisch-zentrum.slavistik.lmu.de/events.html',
				'language' => 'de',
				'category_bias' => 'community',
				'priority' => 7,
				'fetch_interval' => 7200,
				'is_active' => 0,
				'risk_level' => 'low',
				'notes' => 'HTML-страница мероприятий украинского культурного центра. Нужен DOM-парсинг.',
			],
			[
				'name' => 'Hilfe-UA / Refugio München',
				'type' => 'scrape',
				'url' => 'https://hilfe-ua.de/nachrichten/',
				'language' => 'de',
				'category_bias' => 'community',
				'priority' => 7,
				'fetch_interval' => 7200,
				'is_active' => 0,
				'risk_level' => 'low',
				'notes' => 'Волонтёрские и социальные инициативы. Нужен HTML-парсинг для локальных анонсов и помощи.',
			],
			[
				'name' => 'Ukrainische Gemeinde München',
				'type' => 'scrape',
				'url' => 'https://www.erzbistum-muenchen.de/spenden-ukrainische-gemeinde',
				'language' => 'de',
				'category_bias' => 'community',
				'priority' => 6,
				'fetch_interval' => 7200,
				'is_active' => 0,
				'risk_level' => 'low',
				'notes' => 'Религиозная община и гуманитарная помощь. Нужен HTML-парсинг.',
			],
			[
				'name' => 'House of Resources München',
				'type' => 'scrape',
				'url' => 'https://www.hor-muenchen.de/veranstaltungskalender/',
				'language' => 'de',
				'category_bias' => 'community',
				'priority' => 7,
				'fetch_interval' => 7200,
				'is_active' => 0,
				'risk_level' => 'low',
				'notes' => 'Интеграционные диалоги, языковые курсы, встречи и мероприятия. Нужен HTML-парсинг календаря.',
			],
			[
				'name' => 'Telegram Ukrainian Bavaria',
				'type' => 'telegram',
				'url' => 'https://t.me/s/ukrainianbavaria',
				'language' => 'uk',
				'category_bias' => 'community',
				'priority' => 8,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Публичный Telegram-канал с регулярными анонсами событий, интеграции и жизни украинцев в Баварии и Мюнхене.',
			],
			[
				'name' => 'Telegram Moi Dom München',
				'type' => 'telegram',
				'url' => 'https://t.me/s/moidommuc',
				'language' => 'ru',
				'category_bias' => 'community',
				'priority' => 8,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Публичный мюнхенский Telegram-канал с живыми бытовыми объявлениями, локальными анонсами, встречами и полезной информацией для украинцев в Мюнхене.',
			],
			[
				'name' => 'Telegram Ukrainian in Germany Portal',
				'type' => 'telegram',
				'url' => 'https://t.me/s/UKRAINIANinGERMANYportal',
				'language' => 'uk',
				'category_bias' => 'leben-in-deutschland',
				'priority' => 8,
				'fetch_interval' => 3600,
				'is_active' => 1,
				'risk_level' => 'moderate',
				'notes' => 'Публичный Telegram-канал с практическими апдейтами для украинцев в Германии: документы, быт, сервисная информация.',
			],
			[
				'name' => 'Google News Community Bayern DE Focus',
				'type' => 'google_news',
				'url' => 'https://news.google.com/rss/search?q=M%C3%BCnchen+ukrainische+Gemeinde+Veranstaltung+Bayern&hl=de&gl=DE&ceid=DE:de',
				'language' => 'de',
				'category_bias' => 'community',
				'priority' => 8,
				'fetch_interval' => 1800,
				'is_active' => 0,
				'risk_level' => 'moderate',
				'notes' => 'Экспериментальный узкий Google News-поиск по общинам и событиям в Баварии и Мюнхене. Держать выключенным, пока не подтвердится качество сигнала.',
			],
		];

		foreach ($sources as &$source) {
			if (($source['type'] ?? '') === 'scrape' && empty($source['parse_rules'])) {
				$source['parse_rules'] = EPV2_Source_Adapters::rules_for((string) ($source['url'] ?? ''));
			}
		}
		unset($source);

		return $sources;
	}

	public static function import(): int {
		$count = 0;
		foreach (self::recommended() as $source) {
			if (! self::should_import($source)) {
				continue;
			}
			if (EPV2_Sources::exists((string) $source['name'], (string) $source['url'])) {
				continue;
			}
			EPV2_Sources::save($source);
			$count++;
		}
		return $count;
	}

	private static function should_import(array $source): bool {
		$name = (string) ($source['name'] ?? '');
		$blocked = [
			'Deutschlandfunk',
			'Handelsblatt',
			'Kicker OPML',
			'FC Bayern Official',
		];
		return ! in_array($name, $blocked, true);
	}
}
